Update GUI with improved labels and load logo image
NSoiffer/MathCATForPython pull request #11
Opened 2022-03-20 18:57 UTC by ways2read

Logo image is now loaded from within MathCATPreferences, so MathCATGUI is untouched after it is generated from wxFormBuilder.
Changed the label of the speech rate option, and changed the logo of the braille highlight option.

2022-03-20 20:28 UTC, NSoiffer requested changes
Looks mostly good, but I see the line
```
import wx.xrc
```
is back. That will generate an error when run in NVDA needs to go away.

Also, why change from point to github to 
```
<property name="path">C:\Users\Rorme\OneDrive - DAISY Consortium\DAISY\Activities\Software tools\MathCAT\MathCATForPython\NVDA-addon\addon\globalPlugins\MathCAT</property>
```

2022-03-20 22:37 UTC, ways2read commented
The import wx.xrc is generated by the wxFormBuilder tool. I don't see anything I can change to stop it from adding this, so I think a build script may be necessary to comment this or remove it.

2022-03-21 03:53 UTC, NSoiffer commented
Fixes look good. I'll look into adding a line to the build script to deal with the import (I'll probably use 'sed')

2022-03-21 03:53 UTC, merged

2022-10-11 08:53 UTC, ways2read commented
The surplus import statement is a known bug in wxFormBuilder
Error in Python creation code · Issue #171 · wxFormBuilder/wxFormBuilder (github.com)<https://github.com/wxFormBuilder/wxFormBuilder/issues/171>

It was logged nearly 10 years ago, so I think your fix in the build script may be the fastest approach 😉

2022-10-12 20:50 UTC, NSoiffer commented
Ok. Since it is working, leaving it is faster than fixing it ;-)

I have a request for another item for the dialog: "Say 'cap' for math
speech" followed by a checkbox. The chemistry group feels this is
important. But don't add it quite yet. I just added a checkbox to the
MathCATDemo page (probably will show up Thursday your time) along with an
automatic pitch change for caps so they can test out what pitch change vs
"cap" is like.

    Neil


On Tue, Oct 11, 2022 at 1:53 AM Richard Orme ***@***.***>
wrote:

> The surplus import statement is a known bug in wxFormBuilder
> Error in Python creation code · Issue #171 · wxFormBuilder/wxFormBuilder (
> github.com)<https://github.com/wxFormBuilder/wxFormBuilder/issues/171>
>
> It was logged nearly 10 years ago, so I think your fix in the build script
> may be the fastest approach 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NSoiffer/MathCATForPython/pull/11#issuecomment-1274340818>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALZM3CQN35I72XFRUCGX23WCUTJZANCNFSM5RF4I73A>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>